---
- name: Rollback {{ app }}
  hosts: web
  remote_user: root

  vars_files:
    - ./deploy_vars/{{ app }}.yml

  roles:
    - {
      role: carlosbuenosvinos.ansistrano-rollback,
      ansistrano_deploy_to: "/var/www/deploy/{{ deploy_environment }}/{{ app }}"
     }
