mysql_enablerepo: "remi"
mysql_root_password: "{{ pw_mysql_root }}"
mysql_root_password_update: yes
mysql_databases:
  - name: myapp
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: myapp
    host: "%"
    password: "{{ pw_mysql_myapp }}"
    priv: "myapp.*:ALL"
